import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, CircularProgress, FormControl, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import RefreshIcon from "@mui/icons-material/Refresh";
import { getApiStats } from "./apiStatsService";
import type { ApiResourceStat, ApiStatsFilters, CollectionRun, DatePreset, HourlyMatrixDatum, SystemStat } from "./types";
import { aggregateResourceStats, dateInputToIst, formatIst, istDateInput, istDayRange } from "./utils";
import { ApiStatsSummaryCards } from "./ApiStatsSummaryCards";
import { ApiStatsHourlyMatrix } from "./ApiStatsHourlyMatrix";
import { ApiStatsDetailsTable } from "./ApiStatsDetailsTable";
import { ApiStatsDetailsDrawer } from "./ApiStatsDetailsDrawer";
import { ApiStatsSystemActivity } from "./ApiStatsSystemActivity";
import { ApiStatsCollectionHealth } from "./ApiStatsCollectionHealth";

const today = istDayRange();
const initialFilters: ApiStatsFilters = { ...today, preset: "today", resource: "", method: "", outcome: "all", hour: null };

export const ApiStatsPage = () => {
  const [filters,setFilters]=useState(initialFilters); const [resources,setResources]=useState<ApiResourceStat[]>([]); const [matrix,setMatrix]=useState<HourlyMatrixDatum[]>([]); const [systems,setSystems]=useState<SystemStat[]>([]); const [health,setHealth]=useState<CollectionRun[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [selected,setSelected]=useState<ApiResourceStat|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await getApiStats(filters);setResources(data.resources);setMatrix(data.matrix);setSystems(data.systems);setHealth(data.health);}catch(e){setError(e instanceof Error?e.message:"Unable to load API statistics");}finally{setLoading(false);}},[filters]);
  useEffect(()=>{void load();},[load]);
  const aggregatedResources=useMemo(()=>aggregateResourceStats(resources),[resources]); const resourceOptions=useMemo(()=>[...new Set(resources.map(r=>r.resource))].sort(),[resources]); const methodOptions=useMemo(()=>[...new Set(resources.map(r=>r.method))].sort(),[resources]); const latest=health[0];
  const setPreset=(preset:DatePreset)=>{let range=today;if(preset==="yesterday")range=istDayRange(-1);if(preset==="7days")range={start:new Date(today.start.getTime()-6*86400000),end:today.end};setFilters(f=>({...f,...range,preset}));};
  const showFromMatrix=(bucket:string|null,resource:string|null)=>{const row=resources.find(r=>(!bucket||r.bucket_start===bucket)&&(!resource||r.resource===resource));if(row)setSelected(row);};
  return <Box sx={{maxWidth:1800,mx:"auto",pb:4}}><Stack direction={{xs:"column",md:"row"}} justifyContent="space-between" gap={2} mb={2}><Box><Typography variant="h4" fontWeight={750}>API Statistics</Typography><Typography color="text.secondary">Privacy-safe aggregate activity. All dates and times use Asia/Kolkata.</Typography><Typography variant="body2" mt={.5}>Last successful collection: {formatIst(health.find(r=>r.status.toLowerCase()==="success")?.completed_at??null)} · Latest status: {latest?.status??"No data"}</Typography></Box><Button variant="outlined" startIcon={<RefreshIcon/>} onClick={()=>void load()} disabled={loading}>Refresh</Button></Stack>
  <Paper variant="outlined" sx={{p:2,borderRadius:2,mb:2}}><Stack direction={{xs:"column",sm:"row"}} flexWrap="wrap" gap={1.5}>{(["today","yesterday","7days","custom"] as DatePreset[]).map(p=><Button key={p} size="small" variant={filters.preset===p?"contained":"outlined"} onClick={()=>setPreset(p)}>{p==="7days"?"Last 7 days":p[0].toUpperCase()+p.slice(1)}</Button>)}<TextField size="small" type="date" label="From (IST)" value={istDateInput(filters.start)} onChange={e=>setFilters(f=>({...f,start:dateInputToIst(e.target.value),preset:"custom"}))} InputLabelProps={{shrink:true}}/><TextField size="small" type="date" label="To (IST)" value={istDateInput(new Date(filters.end.getTime()-1))} onChange={e=>setFilters(f=>({...f,end:dateInputToIst(e.target.value,true),preset:"custom"}))} InputLabelProps={{shrink:true}}/>
  <FormControl size="small" sx={{minWidth:160}}><InputLabel>Resource</InputLabel><Select label="Resource" value={filters.resource} onChange={e=>setFilters(f=>({...f,resource:e.target.value}))}><MenuItem value="">All resources</MenuItem>{resourceOptions.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{minWidth:120}}><InputLabel>Method</InputLabel><Select label="Method" value={filters.method} onChange={e=>setFilters(f=>({...f,method:e.target.value}))}><MenuItem value="">All</MenuItem>{methodOptions.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{minWidth:140}}><InputLabel>Outcome</InputLabel><Select label="Outcome" value={filters.outcome} onChange={e=>setFilters(f=>({...f,outcome:e.target.value as ApiStatsFilters["outcome"]}))}><MenuItem value="all">All</MenuItem><MenuItem value="success">Success</MenuItem><MenuItem value="failure">Failure</MenuItem></Select></FormControl><FormControl size="small" sx={{minWidth:110}}><InputLabel>Hour</InputLabel><Select label="Hour" value={filters.hour??""} onChange={e=>setFilters(f=>({...f,hour:e.target.value===""?null:Number(e.target.value)}))}><MenuItem value="">All</MenuItem>{Array.from({length:24},(_,i)=><MenuItem key={i} value={i}>{String(i).padStart(2,"0")}:00</MenuItem>)}</Select></FormControl></Stack></Paper>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{loading?<Box display="flex" justifyContent="center" py={8}><CircularProgress/></Box>:resources.length+systems.length+health.length===0?<Alert severity="info">No aggregate data is available for these filters.</Alert>:<Stack spacing={2}><ApiStatsSummaryCards rows={aggregatedResources} latest={latest}/><ApiStatsHourlyMatrix data={matrix} onSelect={showFromMatrix}/><Box sx={{overflowX:"auto"}}><ApiStatsDetailsTable rows={aggregatedResources} onSelect={setSelected}/></Box><ApiStatsSystemActivity rows={systems}/><ApiStatsCollectionHealth rows={health} expectedStart={filters.start} expectedEnd={filters.end}/></Stack>}<ApiStatsDetailsDrawer row={selected} onClose={()=>setSelected(null)}/></Box>;
};
